# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonId', models.IntegerField()),
                ('queueId', models.IntegerField()),
                ('gameId', models.IntegerField()),
                ('gameVersion', models.CharField(max_length=20)),
                ('platformId', models.IntegerField()),
                ('gameMode', models.CharField(max_length=20)),
                ('mapId', models.IntegerField()),
                ('gameType', models.CharField(max_length=20)),
                ('gameDuration', models.IntegerField()),
                ('gameCreation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('championId', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.Match')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantIdentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantId', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.Match')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.BooleanField()),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.Participant')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentPlatformId', models.CharField(max_length=20)),
                ('summonerName', models.CharField(max_length=100)),
                ('matchHistoryUri', models.CharField(max_length=100)),
                ('platformId', models.CharField(max_length=20)),
                ('currentAccountId', models.IntegerField()),
                ('profileIcon', models.IntegerField()),
                ('summonerId', models.IntegerField()),
                ('accountId', models.IntegerField()),
                ('participantIdentity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.ParticipantIdentity')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.BooleanField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.Match')),
            ],
        ),
    ]
