# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pb_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='gameCreation',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='gameDuration',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='gameId',
            field=models.BigIntegerField(),
        ),
    ]
