# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pb_analyzer', '0002_auto_20171124_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='gameCreation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='gameDuration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='gameId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='platformId',
            field=models.CharField(max_length=20),
        ),
    ]
