# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pb_analyzer', '0003_auto_20171124_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participantId', models.IntegerField()),
                ('lane', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.Participant')),
            ],
        ),
        migrations.RemoveField(
            model_name='teamstats',
            name='match',
        ),
        migrations.DeleteModel(
            name='TeamStats',
        ),
    ]
