# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pb_analyzer', '0005_auto_20171125_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='current_platformId',
            new_name='current_platform_id',
        ),
    ]
