# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pb_analyzer', '0007_summoner'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='account_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summoner',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summoner',
            name='summoner_level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
