# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pb_analyzer', '0008_auto_20171125_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummnerMatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.Match')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.Participant')),
            ],
        ),
        migrations.AlterField(
            model_name='participantstats',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.Participant'),
        ),
        migrations.AlterField(
            model_name='participanttimeline',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.Participant'),
        ),
        migrations.AlterField(
            model_name='player',
            name='participant_identity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.ParticipantIdentity'),
        ),
        migrations.AddField(
            model_name='summnermatchresult',
            name='stats',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.ParticipantStats'),
        ),
        migrations.AddField(
            model_name='summnermatchresult',
            name='summoner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.Summoner'),
        ),
        migrations.AddField(
            model_name='summnermatchresult',
            name='timeline',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.ParticipantTimeline'),
        ),
    ]
