# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pb_analyzer', '0009_auto_20171126_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='summoner_level',
            field=models.IntegerField(null=True),
        ),
    ]
