# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pb_analyzer', '0010_auto_20171126_0824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SummnerMatchResult',
            new_name='SummonerMatchResult',
        ),
    ]
