# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pb_analyzer', '0011_auto_20171126_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summonermatchresult',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.Match'),
        ),
        migrations.AlterField(
            model_name='summonermatchresult',
            name='stats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.ParticipantStats'),
        ),
        migrations.AlterField(
            model_name='summonermatchresult',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.Summoner'),
        ),
        migrations.AlterField(
            model_name='summonermatchresult',
            name='timeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pb_analyzer.ParticipantTimeline'),
        ),
    ]
