# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pb_analyzer', '0012_auto_20171126_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_creation',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_duration',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='account_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='current_account_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='summoner_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='account_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='summoner_level',
            field=models.BigIntegerField(null=True),
        ),
    ]
