# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pb_analyzer', '0013_auto_20171129_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='rank',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='tier',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
