# Generated by Django 2.0.1 on 2018-01-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pb_analyzer', '0014_auto_20171231_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
