# Generated by Django 2.0.1 on 2018-01-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pb_analyzer', '0015_summoner_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
